version: '2'
services:
  celery:
    build:
      context: .
    command:
    - celery
    - -A
    - versionapi.celery
    - worker
    - -l
    - debug
    networks:
    - salt
  api:
    build:
      context: .
    command:
    - python
    - -m
    - versionapi.app
    environment:
      FLASK_DEBUG: 1
    ports:
    - "8200:8200"
    networks:
    - salt
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: daniel
      RABBITMQ_DEFAULT_PASS: braves123
    networks:
    - salt
  postgres:
    image: postgres 
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: braves123
      POSTGRES_DB: version
    networks:
    - salt
networks:
  salt:
