version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.yml
    ports:
    - "80:80"
    networks:
    - salt
  celery:
    build:
      context: .
      dockerfile: docker/app.yml
    command: celery -A versionapi.celeryapp worker -l debug
    networks:
    - salt
  api:
    build:
      context: .
      dockerfile: docker/app.yml
    command: python -m versionapi.app
    volumes:
    - /Users/daniel/github/versionapi:/versionapi
    environment:
      FLASK_DEBUG: 1
    networks:
    - salt
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: daniel
      RABBITMQ_DEFAULT_PASS: braves123
    networks:
    - salt
  postgres:
    image: postgres 
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: braves123
      POSTGRES_DB: version
    networks:
    - salt
networks:
  salt:
