FROM nginx:stable-alpine
ENV DEVEL=1

ADD docker/nginx.conf /etc/nginx/conf.d/version.conf


RUN apk add -U python3 git && \
    rm -f /etc/nginx/conf.d/default.conf && \
    python3 -m ensurepip

WORKDIR /versionapi/
COPY . .
RUN pip3 install .
