apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
      - name: api
        image: docker.io/gtmanfred/versionapi:0.2.2
        command:
        - python
        args: ['-m', 'versionapi.app']
        ports:
        - containerPort: 5000
          name: api
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: BROKER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: broker
        - name: BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres
              key: backend
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
    - port: 5000
  selector:
    app: api
    tier: backend
  type: LoadBalancer
