apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
      - name: postgres
        image: docker.io/postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: user
        - name: POSTGRES_DB
          value: version
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: rabbitmq
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    tier: backend
