apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: celery
spec:
  selector:
    matchLabels:
      app: celery
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: celery
        tier: backend
    spec:
      containers:
      - name: celery
        image: docker.io/gtmanfred/versionapi:0.2.2
        command:
        - celery
        args: ['-A', 'versionapi.celeryapp', 'worker', '-l', 'debug']
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: BROKER
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: broker
        - name: BACKEND
          valueFrom:
            secretKeyRef:
              name: postgres
              key: backend
