FROM nginx:stable-alpine

ADD nginx.conf /etc/nginx/conf.d/version.conf

RUN apk add -U python3 git && \
    rm -f /etc/nginx/conf.d/default.conf && \
    python3 -m ensurepip && \
    pip3 install git+git://github.com/gtmanfred/versionapi@master#egg=versionapi
